_core:
  default_config_hash: Gw_DjU53-aWorpAZwMrBB4BAbND70Lw7A9C0h2mh5Zg
langcode: uk
settings:
  default_status: open
  default_categories: {  }
  default_page: true
  default_page_base_path: /form
  default_ajax: false
  default_ajax_progress_type: throbber
  default_ajax_effect: fade
  default_ajax_speed: 500
  default_submit_button_label: Надіслати
  default_reset_button_label: Скинути
  default_delete_button_label: Видалити
  default_form_submit_once: false
  default_form_open_message: 'Ця форма ще не відкрита для надсилання.'
  default_form_close_message: 'Вибачте… Ця форма закрита для нових надсилань.'
  default_form_exception_message: "Неможливо відобразити цю вебформу. Будь ласка, зв'яжіться з адміністратором сайту."
  default_form_confidential_message: 'Ця форма є конфіденційною. Щоб надіслати її необхідно <a href="[site:login-url]/logout?destination=[current-page:url:relative]">вийти</a>.'
  default_form_access_denied_message: 'Увійдіть, щоб отримати доступ до цієї форми.'
  default_form_disable_remote_addr: false
  default_form_novalidate: false
  default_form_disable_inline_errors: false
  default_form_required: false
  default_form_required_label: "Вказує обов'язкові для заповнення поля"
  default_form_unsaved: false
  default_form_disable_back: false
  default_form_submit_back: false
  default_form_details_toggle: true
  default_form_file_limit: ''
  default_wizard_prev_button_label: '< Назад'
  default_wizard_next_button_label: 'Далі >'
  default_wizard_start_label: Початок
  default_wizard_confirmation_label: Завершене
  default_wizard_toggle_show_label: 'Показати все'
  default_wizard_toggle_hide_label: 'Сховати все'
  default_preview_next_button_label: 'Попередній перегляд'
  default_preview_prev_button_label: '< Назад'
  default_preview_label: 'Попередній перегляд'
  default_preview_title: '[webform:title]: попередній перегляд'
  default_preview_message: 'Будь ласка, перегляньте своє надсилання. Надсилання не є завершеним, доки не натиснуто кнопку «Надіслати»!'
  default_draft_button_label: 'Зберегти чернетку'
  default_draft_saved_message: 'Надсилання збережені. Ви можете повернутися до цієї форми пізніше, і поточні значення будуть відновлені.'
  default_draft_loaded_message: 'Знайдено частково завершену форму. Будь ласка, завершіть незаповнені частини.'
  default_draft_pending_single_message: 'У вас є чернетка цієї вебформи, що очікує на розгляд. <a href="#">Завантажити чернетку, що очікує на розгляд</a> .'
  default_draft_pending_multiple_message: 'У вас є чернетки цієї вебформи, що очікують на розгляд. <a href="#">Переглянути чернетки, що очікують на розгляд</a> .'
  default_confirmation_message: 'Нове надсилання додано до [webform:title].'
  default_confirmation_back_label: 'Назад до форми'
  default_confirmation_noindex: true
  default_limit_total_message: 'Більше надсилань не дозволяється.'
  default_limit_user_message: 'Більше надсилань не дозволяється.'
  default_submission_label: '[webform_submission:submitted-to]: Надсилання №[webform_submission:serial]'
  default_submission_log: false
  default_submission_views: {  }
  default_submission_views_replace:
    global_routes:
      - entity.webform_submission.collection
      - entity.webform_submission.user
    webform_routes:
      - entity.webform.results_submissions
      - entity.webform.user.drafts
      - entity.webform.user.submissions
    node_routes:
      - entity.node.webform.results_submissions
      - entity.node.webform.user.drafts
      - entity.node.webform.user.submissions
  default_results_customize: false
  default_submission_access_denied_message: 'Увійдіть, щоб отримати доступ до цього надсилання.'
  default_submission_exception_message: "Неможливо обробити це надсилання. Будь ласка, зв'яжіться з адміністратором сайту."
  default_submission_locked_message: 'Це надсилання заблоковано.'
  default_previous_submission_message: 'Ця вебформа вже була надіслана. <a href="#">Переглянути попереднє надсилання</a> .'
  default_previous_submissions_message: 'Ця вебформа вже була надіслана. <a href="#">Переглянути попередні надсилання</a> .'
  default_autofill_message: 'Це надсилання було автоматично заповнено попереднім надсиланням.'
  form_classes: |
    container-inline clearfix
    form--inline clearfix
    messages messages--error
    messages messages--warning
    messages messages--status
  button_classes: ''
  preview_classes: |
    messages messages--error
    messages messages--warning
    messages messages--status
  confirmation_classes: |
    messages messages--error
    messages messages--warning
    messages messages--status
  confirmation_back_classes: |
    button
  default_share: false
  default_share_node: false
  default_share_theme_name: ''
  webform_bulk_form: true
  webform_bulk_form_actions:
    - webform_open_action
    - webform_close_action
    - webform_archive_action
    - webform_unarchive_action
    - webform_delete_action
  webform_submission_bulk_form: true
  webform_submission_bulk_form_actions:
    - webform_submission_make_sticky_action
    - webform_submission_make_unsticky_action
    - webform_submission_make_lock_action
    - webform_submission_make_unlock_action
    - webform_submission_delete_action
  dialog: false
  dialog_options:
    narrow:
      title: Вузький
      width: 600
    normal:
      title: Звичайне
      width: 800
    wide:
      title: Широкий
      width: 1000
assets:
  css: ''
  javascript: ''
form:
  limit: 50
  filter_category: ''
  filter_state: ''
element:
  machine_name_pattern: a-z0-9_
  empty_message: '{Порожньо}'
  allowed_tags: admin
  wrapper_classes: |
    container-inline clearfix
    form--inline clearfix
    messages messages--error
    messages messages--warning
    messages messages--status
  classes: |
    container-inline clearfix
    form--inline clearfix
    messages messages--error
    messages messages--warning
    messages messages--status
  horizontal_rule_classes: |
    webform-horizontal-rule--solid
    webform-horizontal-rule--dashed
    webform-horizontal-rule--dotted
    webform-horizontal-rule--gradient
    webform-horizontal-rule--thin
    webform-horizontal-rule--medium
    webform-horizontal-rule--thick
    webform-horizontal-rule--flaired
    webform-horizontal-rule--glyph
  default_description_display: ''
  default_more_title: Ще
  default_section_title_tag: h2
  default_empty_option: true
  default_empty_option_required: ''
  default_empty_option_optional: ''
  excluded_elements:
    password: password
    password_confirm: password_confirm
html_editor:
  disabled: false
  element_format: webform_default
  mail_format: webform_default
  tidy: true
  make_unused_managed_files_temporary: true
file:
  file_public: false
  file_private_redirect: true
  file_private_redirect_message: 'Увійдіть, щоб отримати доступ до викладеного файлу.'
  default_max_filesize: ''
  default_managed_file_extensions: 'gif jpg jpeg png bmp eps tif pict psd txt rtf html odf pdf doc docx ppt pptx xls xlsx xml avi mov mp3 mp4 ogg wav bz2 dmg gz jar rar sit svg tar zip'
  default_image_file_extensions: 'gif jpg jpeg png'
  default_video_file_extensions: 'avi mov mp4 ogg wav webm'
  default_audio_file_extensions: 'mp3 ogg wav'
  default_document_file_extensions: 'txt rtf pdf doc docx odt ppt pptx odp xls xlsx ods'
  make_unused_managed_files_temporary: true
  delete_temporary_managed_files: true
format: {  }
mail:
  default_to_mail: '[site:mail]'
  default_from_mail: '[site:mail]'
  default_from_name: '[site:name]'
  default_reply_to: ''
  default_return_path: ''
  default_sender_mail: ''
  default_sender_name: ''
  default_subject: 'Надсилання вебформи з: [webform_submission:source-title]'
  default_body_text: "Надіслано [webform_submission:created]\r\nНадіслав: [webform_submission:user]\r\n\r\nНадіслані значення:\r\n[webform_submission:values]\n"
  default_body_html: |
    <p>Submitted on [webform_submission:created]</p>
    <p>Submitted by: [webform_submission:user]</p>
    <p>Submitted values are:</p>
    [webform_submission:values]
  roles: {  }
export:
  temp_directory: ''
  exporter: delimited
  delimiter: ','
  multiple_delimiter: ;
  excel: false
  archive_type: tar
  header_format: label
  header_prefix: true
  header_prefix_key_delimiter: __
  header_prefix_label_delimiter: ': '
  entity_reference_items:
    - id
    - title
    - url
  options_single_format: compact
  options_multiple_format: compact
  options_item_format: label
  likert_answers_format: label
  signature_format: status
  composite_element_item_format: label
  excluded_exporters: {  }
handler:
  excluded_handlers: {  }
variant:
  excluded_variants: {  }
batch:
  default_batch_export_size: 500
  default_batch_import_size: 100
  default_batch_update_size: 500
  default_batch_delete_size: 500
  default_batch_email_size: 500
purge:
  cron_size: 100
test:
  types: "checkbox:\r\n  - true\r\ncolor:\r\n  - '#ffffcc'\r\n  - '#ffffcc'\r\n  - '#ccffff'\r\nemail:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nlanguage_select:\r\n  - en\r\nmachine_name:\r\n  - 'loremipsum'\r\n  - 'oratione'\r\n  - 'dixisset'\r\ntel:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ntextarea:\r\n  - 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.'\r\n  - 'Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;'\r\n  - 'Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.'\r\ntext_format:\r\n  - value: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.</p>'\r\n  - value: '<p>Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;</p>'\r\n  - value: '<p>Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.</p>'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\nwebform_email_confirm:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nwebform_email_multiple:\r\n  - 'example@example.com, test@test.com, random@random.com'\r\nwebform_time:\r\n  - '09:00'\r\n  - '17:00'\n"
  names: "first_name:\r\n  - 'Джон'\r\n  - 'Пол'\r\n  - 'Рінго'\r\n  - 'Джордж'\r\nlast_name:\r\n  - 'Леннон'\r\n  - 'Маккартні'\r\n  - 'Старр'\r\n  - 'Гарісон'\r\naddress:\r\n  - 'Мейн стріт, 10'\r\n  - 'Брук Еллі Роуд, 11, КВ.1'\r\nzip:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\npostal_code:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\nphone:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\nfax:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ncity:\r\n  - 'Спрінгфілд'\r\n  - 'Плезентвіль'\r\n  - 'Гілл Воллі'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\ndefault:\r\n  - 'Loremipsum'\r\n  - 'Oratione'\r\n  - 'Dixisset'\n"
ui:
  video_display: dialog
  help_disabled: false
  dialog_disabled: false
  offcanvas_disabled: false
  promotions_disabled: false
  support_disabled: false
  details_save: true
  description_help: true
  toolbar_item: false
libraries:
  excluded_libraries:
    - choices
    - jquery.chosen
requirements:
  cdn: true
  clientside_validation: true
  bootstrap: true
  spam: true
third_party_settings:
  captcha:
    replace_administration_mode: true
